[package]
name = "conditional_remote_poc"
version = "0.1.0"
edition = "2023_10"

[cairo]
sierra = true

[dependencies]
# Using Cairo core only. Poseidon is provided in core::poseidon.

[dev-dependencies]
cairo_test = "2.11.4"
